### ISSUE TITLE
German SP Source

### ISSUE THREAD

**Issue by Rasp-lok** [f-person/parkview_enhancer#1]
Hi, German website is not "www.southparkstudios.de" but "www.southpark.de" is. 
Can you please change it to the legit one ;) or how may I edit that as a rookie ?

**Comment by f-person** [comment]
Hi! I just added it. I'm not actively working on the extension anymore, though, since Paramount sent me a DMCA takedown request & Google accepted it. Is it still useful for you?

**Comment by Rasp-lok** [comment]
Thanks for so quick response. Shame on PAaramount, amazinh what you did. 
I don't know yet whether it works. 
I somehow couldn't include the latest json to the extension manually. any chance i get latest status as xpi any guidance ?

**Comment by Rasp-lok** [comment]
Or even maybe the best (since ff didn't remove it) you can update ff with the new manifest 🙏 
If extension works, I'll start to watch it from the beginning again !

**Comment by f-person** [comment]
Yup, I'll roll out an update soonish (and also check what is broken / how easy would the fix be). They updated their player, so some player-related features won't work anymore, but most other stuff should.
